### ISSUE TITLE
Enable teachers to update grades

### ISSUE THREAD

**Issue by chideraeze** [chideraeze/cosc381ScrumandGithubflow#1]
**User Story**

As a teacher, I tend to lose my paper records, So, I want to update the grades online so that the grades will be stored even if I lose the paper records. 

* Persona: teacher who tends to lose paper records
* Feature:  update the grades online
* Business value: the grades will be stored even if the paper records are lost  

**Task List**

- [x] Make sure the database schemes handle grades update
- [ ] Create HTML view for updating grades
- [ ] Connect the HTML views to the database/backend to finish the function ...

**Acceptance Criteria**
1. only for the current semester 
2. only works for chrome

**Acceptance Test**
1. the teacher should be able to finish updating existing grades for students in the course 
2. the teacher should be able to remove existing grades for students in the course
3. the teacher should be able to add new grades for student in the course
